#!/usr/bin/php
<?php
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));
require_once "class.jsonToGoogleTasksManager.php";

$json2TaskMgr = new jsonToGoogleTasksManager();
$json2TaskMgr->loadArrayOfMockTaskData();
$json2TaskMgr->authorize();
$json2TaskMgr->loadOldTasklists();
foreach( $json2TaskMgr->tasks as $taskRow ){
    $tasklist = $taskRow["key"];
    $json2TaskMgr->makeEmptyTaskListIfNeeded( $tasklist );
    $json2TaskMgr->addTaskToList( $tasklist, $taskRow["value"] );
}
exit(0);
?>
