#!/usr/bin/php
<?php
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));
require_once "class.jsonToGoogleTasksManager.php";

$json2TaskMgr = new jsonToGoogleTasksManager();
var_dump( $json2TaskMgr->authorize() );

exit(0);
?>
